name: cloudforamtion-deploy

on:
  push:
    branches:
      - "*"

env:
  WORKFLOW_LEVEL: workflow-level-variable

jobs:
  deploy:
    name: Package and Deploy
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    env:
      JOB_LEVEL: job-level-variable
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: "ap-southeast-1"
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Retrieve paremeters from AWS Secrets Manager
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids: |
            CF_PARAMETERS,arn:aws:secretsmanager:ap-southeast-1:843819829701:secret:dev/app-test-7TDi0A

      - name: Debug env
        env:
          SECRETS_LIST_CLEAN_UP: ""
        run: |
          env
          echo $CF_PARAMETERS >> my-parameters.txt
          cat my-parameters.txt

